language: cpp
  
before_install:
  - pushd ${HOME}
  - wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
  - wget https://github.com/Kitware/CMake/releases/download/v3.19.1/cmake-3.19.1-Linux-x86_64.tar.gz
  - popd
  
install:
  - pushd ${HOME}
  - tar -xf clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
  - export PATH="${PWD}/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04/bin:${PATH}"
  - tar -xf cmake-3.19.1-Linux-x86_64.tar.gz
  - export PATH="${PWD}/cmake-3.19.1-Linux-x86_64/bin:${PATH}"
  - popd
  - pip install conan

before_script:
  - mkdir build
  - cd build
  - conan install .. --build=missing
  - cmake ..
  
script:
  - make
